-- Add theme and advanced layout settings to homepage_settings table
ALTER TABLE homepage_settings
ADD COLUMN IF NOT EXISTS hero_image_url TEXT,
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS favicon_url TEXT,
ADD COLUMN IF NOT EXISTS primary_color_light TEXT DEFAULT 'oklch(0.55 0.15 75)',
ADD COLUMN IF NOT EXISTS primary_color_dark TEXT DEFAULT 'oklch(0.55 0.15 75)',
ADD COLUMN IF NOT EXISTS background_color_light TEXT DEFAULT 'oklch(0.97 0.01 85)',
ADD COLUMN IF NOT EXISTS background_color_dark TEXT DEFAULT 'oklch(0.24 0.04 175)',
ADD COLUMN IF NOT EXISTS card_color_light TEXT DEFAULT 'oklch(0.98 0.01 85)',
ADD COLUMN IF NOT EXISTS card_color_dark TEXT DEFAULT 'oklch(0.26 0.04 175)',
ADD COLUMN IF NOT EXISTS text_color_light TEXT DEFAULT 'oklch(0.2 0 0)',
ADD COLUMN IF NOT EXISTS text_color_dark TEXT DEFAULT 'oklch(0.95 0 0)',
ADD COLUMN IF NOT EXISTS accent_color_light TEXT DEFAULT 'oklch(0.55 0.15 75)',
ADD COLUMN IF NOT EXISTS accent_color_dark TEXT DEFAULT 'oklch(0.55 0.15 75)',
ADD COLUMN IF NOT EXISTS border_radius TEXT DEFAULT '0.625rem',
ADD COLUMN IF NOT EXISTS font_heading TEXT DEFAULT 'Playfair Display',
ADD COLUMN IF NOT EXISTS font_body TEXT DEFAULT 'Inter',
ADD COLUMN IF NOT EXISTS custom_css TEXT,
ADD COLUMN IF NOT EXISTS meta_title TEXT DEFAULT 'Styllus Estética e Beleza',
ADD COLUMN IF NOT EXISTS meta_description TEXT DEFAULT 'Agende seus serviços de estética e beleza online',
ADD COLUMN IF NOT EXISTS meta_keywords TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS social_facebook TEXT,
ADD COLUMN IF NOT EXISTS social_instagram TEXT,
ADD COLUMN IF NOT EXISTS social_whatsapp TEXT;
